// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	updateSettings: (patch: SettingsPatch) => __TAURI_INVOKE<Settings>("update_settings", { patch }),
	getPrivacyRules: () => __TAURI_INVOKE<PrivacyRules>("get_privacy_rules"),
	updatePrivacyRules: (rules: PrivacyRules) => __TAURI_INVOKE<PrivacyRules>("update_privacy_rules", { rules }),
	getConnectionStatus: () => __TAURI_INVOKE<ConnectionStatusView>("get_connection_status"),
	startPairing: (serverUrl: string, pairingCode: string, deviceName: string) => __TAURI_INVOKE<PairingResultView>("start_pairing", { serverUrl, pairingCode, deviceName }),
	removePairing: () => __TAURI_INVOKE<null>("remove_pairing"),
	enableLiveDesk: () => __TAURI_INVOKE<null>("enable_live_desk"),
	disableLiveDesk: () => __TAURI_INVOKE<null>("disable_live_desk"),
	getPreview: () => __TAURI_INVOKE<PreviewView>("get_preview"),
	setPaused: (paused: boolean) => __TAURI_INVOKE<Settings>("set_paused", { paused }),
	quitApp: () => __TAURI_INVOKE<null>("quit_app"),
};

/* Types */
export type ApiError = {
	code: string,
	message: string,
};

export type AppRule = {
	application: Level,
	windowTitle: Level,
	media: Level,
	displayAlias: string | null,
};

export type ConnectionStatusView = {
	paired: boolean,
	baseUrl: string | null,
	deviceId: string | null,
	liveDeskEnabled: boolean,
	coordinator: LiveDeskStatus,
	appVersion: string,
};

export type CoordinatorState = "disabled" | "connecting" | "active" | "degraded" | "updateRequired" | "serverFeatureUnavailable" | "suspended";

export type GlobalDefaults = {
	application: Level,
	windowTitle: Level,
	media: Level,
};

export type Level = "inherit" | "share" | "hide";

export type LiveDeskStatus = {
	state: CoordinatorState,
	lastErrorCode: string | null,
	lastSentAt: string | null,
	mediaCapable: boolean,
	serverBaseUrl: string | null,
	deviceId: string | null,
};

export type PairingResultView = {
	deviceId: string,
};

export type PreviewApplication = {
	displayName: string,
	windowTitle: string | null,
};

export type PreviewMedia = {
	kind: string,
	title: string | null,
	artist: string | null,
	album: string | null,
	player: string | null,
	playing: boolean,
	positionSeconds: number | null,
	durationSeconds: number | null,
};

export type PreviewView = {
	availability: string,
	application: PreviewApplication | null,
	media: PreviewMedia | null,
};

export type PrivacyRules = {
	schemaVersion: number,
	defaults: GlobalDefaults,
	apps: { [key in string]: AppRule },
};

export type Settings = {
	schemaVersion: number,
	shareApplications: boolean,
	shareWindowTitles: boolean,
	shareMedia: boolean,
	ignoreNullArtist: boolean,
	launchAtLogin: boolean,
	pauseSharing: boolean,
	preferredPlayers: string[],
};

export type SettingsPatch = {
	shareApplications: boolean | null,
	shareWindowTitles: boolean | null,
	shareMedia: boolean | null,
	ignoreNullArtist: boolean | null,
	launchAtLogin: boolean | null,
	pauseSharing: boolean | null,
	preferredPlayers: string[] | null,
};

