// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	updateSettings: (patch: SettingsPatch) => __TAURI_INVOKE<Settings>("update_settings", { patch }),
	getPrivacyRules: () => __TAURI_INVOKE<PrivacyRules>("get_privacy_rules"),
	updatePrivacyRules: (rules: PrivacyRules) => __TAURI_INVOKE<PrivacyRules>("update_privacy_rules", { rules }),
	getConnectionStatus: () => __TAURI_INVOKE<ConnectionStatusView>("get_connection_status"),
	startPairing: (serverUrl: string, pairingCode: string, deviceName: string) => __TAURI_INVOKE<PairingResultView>("start_pairing", { serverUrl, pairingCode, deviceName }),
	removePairing: () => __TAURI_INVOKE<null>("remove_pairing"),
	enableLiveDesk: () => __TAURI_INVOKE<null>("enable_live_desk"),
	disableLiveDesk: () => __TAURI_INVOKE<null>("disable_live_desk"),
	getPreview: () => __TAURI_INVOKE<PreviewView>("get_preview"),
	setPaused: (paused: boolean) => __TAURI_INVOKE<Settings>("set_paused", { paused }),
	listHistory: () => __TAURI_INVOKE<SyncEvent[]>("list_history"),
	clearHistory: () => __TAURI_INVOKE<null>("clear_history"),
	getS3Config: () => __TAURI_INVOKE<S3ConfigView>("get_s3_config"),
	updateS3Config: (patch: S3ConfigPatch) => __TAURI_INVOKE<S3ConfigView>("update_s3_config", { patch }),
	quitApp: () => __TAURI_INVOKE<null>("quit_app"),
};

/* Types */
/**  命令边界错误：code 是前端分支依据（对齐 NTEye 的 ApiError 约定）。 */
export type ApiError = {
	code: string,
	message: string,
};

export type AppRule = {
	application: Level,
	windowTitle: Level,
	media: Level,
	displayAlias: string | null,
};

export type ConnectionStatusView = {
	paired: boolean,
	baseUrl: string | null,
	deviceId: string | null,
	liveDeskEnabled: boolean,
	/**  已开启但策略指纹与当前不符 → 需要重新确认 */
	consentStale: boolean,
	coordinator: LiveDeskStatus,
	appVersion: string,
};

export type CoordinatorState = 
/**  未配对或未开启 */
"disabled" | 
/**  能力协商中 */
"connecting" | "active" | "degraded" | 
/**  客户端版本低于服务端最低要求 */
"updateRequired" | 
/**  服务端 schema/特性不可用 */
"serverFeatureUnavailable" | 
/**  睡眠/锁屏/手动暂停 */
"suspended";

/**  全局默认三开关（对齐 macOS：application=share / windowTitle=hide / media=share）。 */
export type GlobalDefaults = {
	application: Level,
	windowTitle: Level,
	media: Level,
};

export type Level = "inherit" | "share" | "hide";

export type LiveDeskStatus = {
	state: CoordinatorState,
	/**  固定错误码（刻意最小化，不含快照内容/端点/响应体） */
	lastErrorCode: string | null,
	/**  RFC3339 UTC 毫秒（chrono DateTime 不便直穿 specta，前端再解析） */
	lastSentAt: string | null,
	mediaCapable: boolean,
	artworkCapable: boolean,
	serverBaseUrl: string | null,
	deviceId: string | null,
};

export type PairingResultView = {
	deviceId: string,
};

export type PreviewApplication = {
	displayName: string,
	windowTitle: string | null,
};

export type PreviewMedia = {
	kind: string,
	title: string | null,
	artist: string | null,
	album: string | null,
	player: string | null,
	playing: boolean,
	positionSeconds: number | null,
	durationSeconds: number | null,
};

export type PreviewView = {
	fingerprint: string,
	availability: string,
	application: PreviewApplication | null,
	media: PreviewMedia | null,
};

export type PrivacyRules = {
	schemaVersion: number,
	defaults: GlobalDefaults,
	apps: { [key in string]: AppRule },
};

export type S3ConfigPatch = {
	endpoint: string | null,
	bucket: string | null,
	region: string | null,
	customDomain: string | null,
	basePath: string | null,
	accessKey: string | null,
	/**  明文仅在内存中；空字符串/None 表示保持不变 */
	secretKey: string | null,
};

export type S3ConfigView = {
	endpoint: string | null,
	bucket: string,
	region: string,
	customDomain: string | null,
	basePath: string,
	accessKey: string,
	hasCredentials: boolean,
};

export type Settings = {
	schemaVersion: number,
	/**  「应用程序」源 */
	shareApplications: boolean,
	/**  「窗口标题」源（默认关，对齐 macOS windowTitle=hide） */
	shareWindowTitles: boolean,
	/**  「媒体」源 */
	shareMedia: boolean,
	/**  无歌手的媒体整体不上报 */
	ignoreNullArtist: boolean,
	launchAtLogin: boolean,
	pauseSharing: boolean,
	/**  偏好播放器（对媒体会话 SourceAppUserModelId 不区分大小写子串匹配） */
	preferredPlayers: string[],
};

export type SettingsPatch = {
	shareApplications: boolean | null,
	shareWindowTitles: boolean | null,
	shareMedia: boolean | null,
	ignoreNullArtist: boolean | null,
	launchAtLogin: boolean | null,
	pauseSharing: boolean | null,
	preferredPlayers: string[] | null,
};

export type SyncEvent = {
	id: string,
	destination: string,
	trigger: SyncTrigger,
	state: SyncState,
	errorCode: string | null,
	/**  仅 Succeeded 存在；来自最终渲染的安全摘要 */
	outputSummary: string | null,
	startedAt: string,
	finishedAt: string,
};

export type SyncState = "succeeded" | "failed" | "skipped";

export type SyncTrigger = "semanticChange" | "heartbeat" | "lifecycle" | "manual";

